Task 2 2 fragment navigation
nastyasteshchenko/android-application-development pull request #3
Opened 2024-10-07 09:26 UTC by nastyasteshchenko

2024-10-09 13:34 UTC, Romchirik requested changes

2024-10-09 13:34 UTC, Romchirik commented on fragment-navigation/app/src/main/java/ru/nsu/fragment/navigation/MainActivity.kt
> +            .replace(R.id.fragment_container, FragmentA())
Хм, а почему не add?

2024-10-09 13:34 UTC, Romchirik commented on fragment-navigation/app/src/main/java/ru/nsu/fragment/navigation/MainActivity.kt
> +            .replace(R.id.fragment_container, FragmentA())
А, понял почему не add. В целом, поведение у этой штуки правильное, но надо бы перейти на add, и делать popBackStack до фрагмента, который был добавлен самым первым (можно тегом его пометить)

Делать так лучше, потому что в случае replace фрагмент пересоздается и его состояние теряется при откате транзакии. С add такого не происходит и при возврате к предыдущему фрагменту мы увидим тот же инстанс, что и до этого

2024-10-09 13:34 UTC, Romchirik commented on fragment-navigation/app/src/main/java/ru/nsu/fragment/navigation/MainActivity.kt
> +            .replace(R.id.fragment_container, FragmentA())
По логике все гуд

2024-10-10 11:57 UTC, nastyasteshchenko commented
Не уверена что сделала как надо, но вот, можно проверять

2024-10-17 12:16 UTC, Romchirik commented on fragment-navigation/app/src/main/java/ru/nsu/fragment/navigation/FragmentB.kt
> +    override fun onCreateView(
Я не помню почему тут нет этого коммента, но этот момент тоже нужно поправить. onCreateView - последний метод до того как у пользователя появится UI и нагружать его чем-то кроме инфлейта не стоит, так ты откладываешь показ хоть какого-то UI пользователю. Тут операций мало, это никак не повлияет на перфоманс, но в боевом приложении можно сильно просесть по метрикам. 

 Для настройки UI и наполнения его данными есть другой метод - onViewCreated, всю логику за исключением создания вьюхи нужно перенести туда

2024-10-17 12:28 UTC, Romchirik commented on fragment-navigation/app/src/main/java/ru/nsu/fragment/navigation/Tag.kt
> +enum class Tag(val tag: String) {
Обычно в отдельный класс выносят какие нить глобальные для приложения штуки (например, токен какой-нить или базовый урл для эндпоинтов). Ну и ограниченность множества енамов никак тут не используется, по сути он просто строку хранит

Лучше перенести тэги в companion object соответствующих фрагментов, тогда к тэгу можно будет обратиться как FragmentName.TAG

2024-11-03 17:45 UTC, Romchirik approved these changes

2024-11-05 10:25 UTC, merged