Task 3 recycler view
nastyasteshchenko/android-application-development pull request #4
Opened 2024-10-08 17:38 UTC by nastyasteshchenko

2024-10-09 16:05 UTC, Romchirik requested changes
Все супер, оч хорошо сделано, микроправки закинуть и можно сдавать

2024-10-09 16:05 UTC, Romchirik commented on recycler-view/app/src/main/java/ru/nsu/recycler/view/adapter/PlayerAdapter.kt
> +            is Song -> ItemType.SONG.ordinal
Вот эта штука опасная довольно, лучше самому прописать в enum какое нить intValue, ординал может поменяться после рефакторинга, и, например, если ты енамку сохраняешь в базу, у тебя все поломается если забудешь про миграцию

2024-10-09 16:05 UTC, Romchirik commented on recycler-view/app/src/main/java/ru/nsu/recycler/view/item/Item.kt
> +sealed class Item {
Применение силдов - круто, 0 вопросов, но обычно наследников определяют внутри родителя, чтобы обращаться к ним RecyclerItem.Banner. Ну и тут родитель не держит никакого состояния, можно заиспользовать sealed interface

2024-10-09 16:05 UTC, Romchirik commented on recycler-view/app/src/main/java/ru/nsu/recycler/view/item/Song.kt
> +    override fun equals(other: Any?): Boolean {
А зачем это, если Song уже является датаклассом?

2024-10-10 12:09 UTC, nastyasteshchenko commented
Исправила, можно смотреть

2024-10-14 04:00 UTC, Romchirik approved these changes

2024-10-21 08:29 UTC, merged