Task 6 dependency injection
nastyasteshchenko/android-application-development pull request #8
Opened 2024-11-10 11:09 UTC by nastyasteshchenko

2024-11-10 11:12 UTC, nastyasteshchenko commented
Хотела сделать все, что прописано в Бонус, но скоупы пока не до конца понимаю как делать, а времени уже на это тратить не могу, поэтому когда-нибудь потом сделаю, а может и не сделаю...

2024-11-13 11:12 UTC, Romchirik requested changes
Все ок, то что надо увидел, но нужно перепакетить немного. Обычно все что связано с DI выносят в отдельный пакет на уровень пакетов data, domain и presentation, так как DI по-хорошему нельзя отнести ни к какому из слоев приложения, он используется везде. Ну и слои приложения в целом могут жить без него, протсо зависимости руками нужно будет создавать

2024-11-14 16:19 UTC, nastyasteshchenko commented
Можно смотреть

2024-11-22 13:10 UTC, Romchirik approved these changes

2024-12-09 05:04 UTC, merged