Task 7 contact application
nastyasteshchenko/android-application-development pull request #9
Opened 2024-11-17 13:46 UTC by nastyasteshchenko

2024-11-22 13:57 UTC, Romchirik requested changes

2024-11-22 13:57 UTC, Romchirik commented on contact-application/.gitignore
<img width="353" alt="image" src="https://github.com/user-attachments/assets/b5899486-ec38-4996-9638-1a4ebed0c102">
Нашел в коде намеки на кнопку добавления контакта, но чет кнопки не видно

2024-11-22 13:57 UTC, Romchirik commented on contact-application/app/src/main/java/ru/nsu/contact/application/presentation/ContactViewModel.kt
> +        viewModelScope.launch {
Вот этот момент очень хороший, но есть нюанс. Если не указан диспатчер то корутина запускается на дефолтном диспатчере. Для андроида дефолтный диспатчер работает на мейн треде и по итогу ты все равно запускаешь фоновую задачу на главном потоке. 

По итогу тут нужно переключить диспатчер на IO

2024-11-22 13:57 UTC, Romchirik commented on contact-application/app/src/main/java/ru/nsu/contact/application/ui/MainActivity.kt
> +            .add(R.id.fragment_container, contactListFragment, ContactListFragment.TAG)
Такс, все таки вернемся к фрагментам. Делать так не оч хорошо потому что у тебя сразу добавляются все фрагменты в стек и инициализируются. По итогу в боевом приложении, если ты так конечно сделаешь, у тебя будет супер-долгий холождный запуск, что очень плохо, будут АНРки и пользователи будут гореть

Лучше добавлять фрагмент когда он нужен под именованой транзакцией и потом ее откатывать, когда нужно вернуться назад. Если у тебя не сильно сложная навигация как в данном случае, скорее всего даже именованые транзакции будут не нужны, достаточно будет добавить их в стек и добавлять фрагмент в менеджер когда он нужен. При нажатии кнопки назад он дропнется автоматически

Если резюмировать, то нужно избавиться схемы с add+show/hide

2024-11-22 13:57 UTC, Romchirik commented on contact-application/app/src/main/java/ru/nsu/contact/application/di/component/AppComponent.kt
> +@Component(modules = [ProvidesDataModule::class, BindsDataModule::class, DomainModule::class])
Тут пойдет, но лучше делать отдельные компоненты на data/domain/ui слои чтобы случайно не дернуть зависимость с левого слоя

2024-12-01 11:18 UTC, nastyasteshchenko commented on contact-application/.gitignore
Немного пофиксила, ток на таком маленьком экране сейчас кнопки будут заезжать на поля, ибо изначально я делала для экрана побольше, пока некогда с этим разобраться

2024-12-01 11:18 UTC, nastyasteshchenko commented on contact-application/app/src/main/java/ru/nsu/contact/application/di/component/AppComponent.kt
> +@Component(modules = [ProvidesDataModule::class, BindsDataModule::class, DomainModule::class])
Попыталась сделать отдельные компоненты

2024-12-01 11:18 UTC, nastyasteshchenko commented
Можно смотреть

2024-12-08 12:02 UTC, Romchirik approved these changes

2024-12-09 05:04 UTC, merged